import re
from pathlib import Path

from apply_recommendation_v2_surgical_patch import main as _apply_v2


def main() -> None:
    # The existing content-policy step runs before V2 and injects the same AI
    # block with its original names. Normalize that deterministic block so the
    # V2 patch can safely apply its stronger app-wide policy without touching
    # unrelated validator logic.
    path = Path('lib/core/music/music_validator.dart')
    text = path.read_text()
    pattern = re.compile(
        r"const List<String> _vShotsUnofficialAiMarkers = <String>\[.*?\];\n\n"
        r"bool _vShotsLooksLikeUnofficialAi\(String title, String artist, String channel\) \{.*?\n\}\n",
        re.S,
    )
    replacement = """const List<String> _vShotsUnofficialAiMarkers = <String>[\n  'ai generated', 'ai-generated', 'ai generated song', 'ai-generated song',\n  'ai cover', 'ai-cover', 'ai voice', 'ai-voice', 'voice clone', 'voice-clone',\n  'deepfake voice', 'deepfake music', 'generated by ai', 'made with ai',\n  'suno ai', 'suno.com', 'udio ai', 'udio.com', 'ai music generator',\n  'ai music', 'artificial intelligence music',\n];\n\nbool _vShotsLooksLikeUnofficialAi(String title, String artist, String channel) {\n  final haystack = '$title $artist $channel'.toLowerCase();\n  return _vShotsUnofficialAiMarkers.any(haystack.contains);\n}\n"""
    if pattern.search(text):
        text = pattern.sub(replacement, text, count=1)
        path.write_text(text)
    _apply_v2()


__all__ = ['main']
