from pathlib import Path

from apply_recommendation_v2_surgical_patch import main as _apply_v2


def main() -> None:
    path = Path('lib/core/music/music_validator.dart')
    text = path.read_text()
    marker = '// CONTENT_POLICY_PATCH: unofficial AI music is never recommended.'
    class_anchor = 'class MusicContentValidator'
    if marker in text and class_anchor in text:
        start = text.index(marker)
        end = text.index(class_anchor, start)
        replacement = """// CONTENT_POLICY_PATCH: unofficial AI music is never recommended.\nconst List<String> _vShotsUnofficialAiMarkers = <String>[\n  'ai generated', 'ai-generated', 'ai generated song', 'ai-generated song',\n  'ai cover', 'ai-cover', 'ai voice', 'ai-voice', 'voice clone', 'voice-clone',\n  'deepfake voice', 'deepfake music', 'generated by ai', 'made with ai',\n  'suno ai', 'suno.com', 'udio ai', 'udio.com', 'ai music generator',\n  'ai music', 'artificial intelligence music',\n];\n\nbool _vShotsLooksLikeUnofficialAi(String title, String artist, String channel) {\n  final haystack = '$title $artist $channel'.toLowerCase();\n  return _vShotsUnofficialAiMarkers.any(haystack.contains);\n}\n\n"""
        text = text[:start] + replacement + text[end:]
        path.write_text(text)
    _apply_v2()


__all__ = ['main']
