from pathlib import Path
import re

ROOT = Path('.')


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'{label}: anchor not found')
    return text.replace(old, new, 1)


def patch_validator() -> None:
    path = ROOT / 'lib/core/music/music_validator.dart'
    text = path.read_text()

    text = replace_once(
        text,
        "  'ai generated', 'ai-generated', 'ai generated song', 'ai-generated song',\n  'ai cover', 'ai-cover', 'ai voice', 'ai-voice', 'voice clone', 'voice-clone',\n  'deepfake voice', 'deepfake music', 'generated by ai', 'made with ai',\n  'suno ai', 'suno.com', 'udio ai', 'udio.com', 'ai music generator',\n  'ai music', 'artificial intelligence music',\n",
        "  'ai generated', 'ai-generated', 'ai generated song', 'ai-generated song',\n  'ai generated songs', 'ai-generated songs', 'ai song', 'ai songs',\n  'ai music', 'ai-music', 'ai music channel', 'ai-music-channel',\n  'ai cover', 'ai-cover', 'ai covers', 'ai-covers', 'ai voice', 'ai-voice',\n  'voice clone', 'voice-clone', 'deepfake voice', 'deepfake music',\n  'generated by ai', 'made with ai', 'made by ai', 'created with ai',\n  'suno ai', 'suno.com', 'udio ai', 'udio.com',\n  'ai music generator', 'artificial intelligence music', 'ai artist',\n",
        'music_validator.dart: AI markers',
    )

    text = replace_once(
        text,
        "bool _vShotsLooksLikeUnofficialAi(String title, String artist, String channel) {\n  final haystack = '$title $artist $channel'.toLowerCase();\n  return _vShotsUnofficialAiMarkers.any(haystack.contains);\n}\n",
        "bool _vShotsLooksLikeAi(String title, String artist, String channel) {\n  final haystack = '$title $artist $channel'.toLowerCase();\n  return _vShotsUnofficialAiMarkers.any(haystack.contains);\n}\n",
        'music_validator.dart: AI helper',
    )

    text = replace_once(
        text,
        "    // HARD POLICY: unofficial AI uploads are not recommendation content.\n    // Explicitly official/verified catalog items are allowed to continue.\n    if (!isOfficial &&\n        _vShotsLooksLikeUnofficialAi(title, artist, channelTitle)) {\n",
        "    // HARD POLICY: AI-generated songs/channels are never V Shots content,\n    // even if a provider incorrectly marks the uploader as official.\n    if (_vShotsLooksLikeAi(title, artist, channelTitle)) {\n",
        'music_validator.dart: hard AI policy',
    )

    anchor = "  /// Confidence below which an item is not considered music.\n"
    public_method = "  /// Hard app-wide AI gate used by repository-level consumers that\n  /// intentionally preserve non-music/manual semantics but must never expose\n  /// AI-generated songs or AI music channels.\n  bool isAiContent(Map<String, dynamic> track) {\n    final title = (track['title'] as String?) ?? '';\n    final artist = (track['artist'] as String?) ?? '';\n    final channel = (track['channelTitle'] as String?) ??\n        (track['channel'] as String?) ?? '';\n    return _vShotsLooksLikeAi(title, artist, channel);\n  }\n\n"
    if 'bool isAiContent' not in text:
        text = replace_once(text, anchor, public_method + anchor, 'music_validator.dart: public AI gate')
    path.write_text(text)


def patch_repository() -> None:
    path = ROOT / 'lib/core/providers/music_repository.dart'
    text = path.read_text()
    if "import '../music/music_validator.dart';" not in text:
        text = replace_once(
            text,
            "import 'provider_models.dart';\n",
            "import 'provider_models.dart';\nimport '../music/music_validator.dart';\n",
            'music_repository.dart: import',
        )

    anchor = "  final ProviderManager _manager;\n"
    helper = """  static const MusicContentValidator _contentValidator =\n      MusicContentValidator();\n\n  List<Map<String, dynamic>> _withoutAi(\n    Iterable<Map<String, dynamic>> tracks,\n  ) => tracks.where((track) => !_contentValidator.isAiContent(track)).toList();\n\n"""
    if '_withoutAi' not in text:
        text = replace_once(text, anchor, anchor + "\n" + helper, 'music_repository.dart: AI helper')

    text = replace_once(
        text,
        "    return result.orElse(const []).map((t) => t.toTrackMap()).toList();\n",
        "    return _withoutAi(result.orElse(const []).map((t) => t.toTrackMap()));\n",
        'music_repository.dart: search gate',
    )
    text = replace_once(
        text,
        "                tracks: result.data!.tracks.map((t) => t.toTrackMap()).toList(),\n",
        "                tracks: _withoutAi(\n                  result.data!.tracks.map((t) => t.toTrackMap()),\n                ),\n",
        'music_repository.dart: paginated gate',
    )
    text = replace_once(
        text,
        "      tracks: result.orElse(const []).map((t) => t.toTrackMap()).toList(),\n",
        "      tracks: _withoutAi(result.orElse(const []).map((t) => t.toTrackMap())),\n",
        'music_repository.dart: detailed gate',
    )
    # Gate all list-producing provider endpoints without changing playback.
    text = text.replace(
        "    return result.orElse(const []).map((t) => t.toTrackMap()).toList();\n",
        "    return _withoutAi(result.orElse(const []).map((t) => t.toTrackMap()));\n",
    )
    path.write_text(text)


def patch_candidate_generator() -> None:
    path = ROOT / 'lib/core/recommendation/candidate_generator.dart'
    text = path.read_text()
    text = text.replace("import 'dart:math';\n\n", "")
    text = text.replace("  final _random = Random();\n", "")

    # Search intent MUST be considered before broad candidate pools. The old
    # 12-query cap could consume the list before recent searches were reached.
    old_search = """    // 5. Search behavior — the user's own real recent searches are a\n    // strong, direct signal of current interest.\n    final recentSearches = LocalLibrary.instance.recentSearches.value\n        .map((s) => s['query'] as String? ?? '')\n        .where((q) => q.isNotEmpty)\n        .take(2);\n    for (final q in recentSearches) {\n      candidates.add(\n        CandidateQuery(query: q, source: CandidateSource.searchBehavior),\n      );\n    }\n\n"""
    if old_search not in text:
        raise SystemExit('candidate_generator.dart: search block not found')
    text = text.replace(old_search, '', 1)

    search_block = """    // 0. SEARCH INTENT — highest priority because it is the user's\n    // strongest explicit current-interest signal. Keep it before the broad\n    // pools so the final candidate cap can never silently discard it.\n    final recentSearches = LocalLibrary.instance.recentSearches.value\n        .map((s) => s['query'] as String? ?? '')\n        .where((q) => q.isNotEmpty)\n        .take(3);\n    for (final q in recentSearches) {\n      candidates.add(\n        CandidateQuery(query: q, source: CandidateSource.searchBehavior),\n      );\n    }\n\n"""
    anchor = "    // 1. Similar artists (content-based discovery seeded from top\n"
    text = replace_once(text, anchor, search_block + anchor, 'candidate_generator.dart: search priority')

    # Deterministic ranking: recommendation results should not reshuffle on
    # every call when user behavior has not changed.
    text = re.sub(
        r"\s*final template = _genreDiscoveryTemplates\[_random\.nextInt\(\n\s*_genreDiscoveryTemplates\.length,\n\s*\)\];",
        "\n      final template =\n          _genreDiscoveryTemplates[topArtists.indexOf(artist) % _genreDiscoveryTemplates.length];",
        text,
        count=1,
    )
    text = text.replace("\n    candidates.shuffle(_random);\n", "\n")
    path.write_text(text)


def patch_home_feed() -> None:
    path = ROOT / 'lib/features/home/home_feed_service.dart'
    text = path.read_text()

    # Replace dynamic duplicate injection with a canonical semantic de-duper.
    start = text.find("  List<HomeShelf> _mergeDynamicShelves(List<HomeShelf> base) {")
    if start < 0:
        raise SystemExit('home_feed_service.dart: dynamic merge start not found')
    end = text.find("\n  List<HomeShelf> _buildFromCms(", start)
    if end < 0:
        raise SystemExit('home_feed_service.dart: dynamic merge end not found')
    new_merge = r'''  List<HomeShelf> _mergeDynamicShelves(List<HomeShelf> base) {
    // One canonical instance of each personalized shelf. This removes the
    // old dynamic_mfy/dynamic_tfy/... copies that duplicated CMS/default rows.
    final seenIds = <String>{};
    final seenPersonalizedKinds = <HomeShelfKind>{};
    final personalizedKinds = <HomeShelfKind>{
      HomeShelfKind.continueListening,
      HomeShelfKind.madeForYou,
      HomeShelfKind.becauseYouListenedTo,
      HomeShelfKind.trendingForYou,
      HomeShelfKind.discoverSomethingNew,
      HomeShelfKind.artistsForYou,
      HomeShelfKind.officialMusic,
    };

    final kept = <HomeShelf>[];
    for (final shelf in base) {
      if (!seenIds.add(shelf.id)) continue;
      if (personalizedKinds.contains(shelf.kind) &&
          !seenPersonalizedKinds.add(shelf.kind)) {
        continue;
      }
      kept.add(shelf);
    }

    // User-first Home order: resume → personalized → discovery/catalog.
    int priority(HomeShelfKind kind) => switch (kind) {
          HomeShelfKind.continueListening => 0,
          HomeShelfKind.madeForYou => 1,
          HomeShelfKind.becauseYouListenedTo => 2,
          HomeShelfKind.trendingForYou => 3,
          HomeShelfKind.discoverSomethingNew => 4,
          HomeShelfKind.artistsForYou => 5,
          HomeShelfKind.officialMusic => 6,
          HomeShelfKind.catalog => 20,
          HomeShelfKind.manual => 30,
        };

    kept.sort((a, b) {
      final byKind = priority(a.kind).compareTo(priority(b.kind));
      if (byKind != 0) return byKind;
      return 0;
    });
    return kept;
  }
'''
    text = text[:start] + new_merge + text[end:]

    # Public surgical refresh used by Home after a real signal; no whole-feed
    # rebuild and no navigation/tab recreation.
    anchor = "  Future<void> loadShelves(\n"
    refresh = r'''  Future<void> refreshPersonalizedShelves(
    List<HomeShelf> shelves, {
    void Function()? onUpdate,
  }) async {
    final targets = shelves.where((s) {
      switch (s.kind) {
        case HomeShelfKind.madeForYou:
        case HomeShelfKind.becauseYouListenedTo:
        case HomeShelfKind.trendingForYou:
        case HomeShelfKind.discoverSomethingNew:
          return true;
        default:
          return false;
      }
    }).toList();
    if (targets.isEmpty) return;
    RecommendationCache.instance.invalidateProfile();
    final baseExclude = LocalLibrary.instance.recentlyShownIds;
    await Future.wait(
      targets.map(
        (s) => _loadShelf(
          s,
          {...baseExclude},
          force: true,
          onUpdate: onUpdate,
        ),
      ),
    );
  }

'''
    text = replace_once(text, anchor, refresh + anchor, 'home_feed_service.dart: targeted refresh')

    # Remove stale rotation behavior; refreshes should be behavior-driven, not
    # random shelf order changes.
    text = text.replace("  int _homeRotationNonce = 0;\n\n", "")
    text = text.replace("      _homeRotationNonce++;\n", "")
    path.write_text(text)


def patch_home_screen() -> None:
    path = ROOT / 'lib/features/home/home_screen.dart'
    text = path.read_text()

    if "import '../../core/recommendation/signal_store.dart';" not in text:
        text = replace_once(
            text,
            "import '../../core/storage/local_library.dart';\n",
            "import '../../core/storage/local_library.dart';\nimport '../../core/recommendation/signal_store.dart';\n",
            'home_screen.dart: SignalStore import',
        )

    text = replace_once(
        text,
        "    LocalLibrary.instance.recentlyPlayed.addListener(_onLibraryChanged);\n",
        "    LocalLibrary.instance.recentlyPlayed.addListener(_onLibraryChanged);\n    SignalStore.instance.revision.addListener(_onRecommendationSignal);\n    homeScrollToTopSignal.addListener(_onHomeScrollToTop);\n",
        'home_screen.dart: listeners',
    )
    text = replace_once(
        text,
        "    LocalLibrary.instance.recentlyPlayed.removeListener(_onLibraryChanged);\n",
        "    LocalLibrary.instance.recentlyPlayed.removeListener(_onLibraryChanged);\n    SignalStore.instance.revision.removeListener(_onRecommendationSignal);\n    homeScrollToTopSignal.removeListener(_onHomeScrollToTop);\n    _recommendationRefreshTimer?.cancel();\n",
        'home_screen.dart: dispose listeners',
    )

    anchor = "  void _onLibraryChanged() {\n"
    methods = r'''  Timer? _recommendationRefreshTimer;
  bool _recommendationRefreshInFlight = false;

  void _onRecommendationSignal() {
    if (!mounted) return;
    // Signals can arrive in bursts (play + duration + completion). Debounce
    // them into one targeted recommendation refresh instead of rebuilding or
    // reloading the complete Home feed.
    _recommendationRefreshTimer?.cancel();
    _recommendationRefreshTimer = Timer(const Duration(milliseconds: 900), () {
      if (!mounted || _recommendationRefreshInFlight) return;
      _recommendationRefreshInFlight = true;
      unawaited(
        homeFeedService
            .refreshPersonalizedShelves(_shelves, onUpdate: _onShelfUpdate)
            .whenComplete(() => _recommendationRefreshInFlight = false),
      );
    });
  }

  void _onHomeScrollToTop() {
    if (!mounted || !_scrollController.hasClients) return;
    unawaited(
      _scrollController.animateTo(
        0,
        duration: const Duration(milliseconds: 280),
        curve: Curves.easeOutCubic,
      ),
    );
  }

'''
    text = replace_once(text, anchor, methods + anchor, 'home_screen.dart: targeted refresh methods')

    # Faster first content: only the first few user-critical shelves are
    # hydrated up front; the rest are already lazy-loaded by this screen.
    text = text.replace("  static const int _initialShelfCount = 12;", "  static const int _initialShelfCount = 6;")
    text = text.replace("  static const int _lazyBatchSize = 8;", "  static const int _lazyBatchSize = 6;")
    text = text.replace("  static const int _lazyLoadAheadShelves = 4;", "  static const int _lazyLoadAheadShelves = 2;")

    # The hero is the single Made For You surface; the shelf renderer skips it
    # below so there is no duplicate MFY row.
    text = replace_once(
        text,
        "      if (shelf.id == 'dynamic_mfy' &&\n",
        "      if (shelf.kind == HomeShelfKind.madeForYou &&\n",
        'home_screen.dart: MFY hero',
    )
    text = replace_once(
        text,
        "      if ((shelf.id == 'dynamic_tfy' ||\n              shelf.id == 'dynamic_discover' ||\n              shelf.id == 'dynamic_mfy') &&\n",
        "      if ((shelf.kind == HomeShelfKind.madeForYou ||\n              shelf.kind == HomeShelfKind.trendingForYou ||\n              shelf.kind == HomeShelfKind.discoverSomethingNew) &&\n",
        'home_screen.dart: Quick Picks source',
    )
    # Skip the hero source from the normal shelf list.
    text = replace_once(
        text,
        "        .where((s) => !_spotlightIds().contains(s.id))\n",
        "        .where((s) =>\n            !_spotlightIds().contains(s.id) &&\n            s.kind != HomeShelfKind.madeForYou)\n",
        'home_screen.dart: MFY duplicate removal',
    )
    path.write_text(text)


def patch_discovery() -> None:
    path = ROOT / 'lib/features/foryou/for_you_feed_screen.dart'
    text = path.read_text()

    # Remove accidental duplicate initialization blocks that had crept into
    # the safe branch; one shown-song record is the correct behavior.
    first = text.find("    if (batch.isNotEmpty) {\n      final first = batch.first;")
    if first >= 0:
        second = text.find("    if (batch.isNotEmpty) {\n      final first = batch.first;", first + 1)
        if second >= 0:
            end = text.find("    }\n  }\n\n  /// Play tap", second)
            if end < 0:
                raise SystemExit('for_you_feed_screen.dart: duplicate init end not found')
            text = text[:second] + text[end + len("    }\n"):]

    # Discovery "For You" must be sourced from the same recommendation pool
    # as Home. The dedicated Discover exploration engine is only fallback.
    old = """      try {\n        final batch = await _discoverEngine.nextBatch(\n          excludeIds: _seenIds,\n          count: 12,\n          languages: _applied.languages.map((l) => l.token).toList(),\n          moods: biases,\n          regions: _applied.genres.map((g) => g.token).toList(),\n          config: engineConfig,\n        );\n        if (batch.isNotEmpty) return _refineForMode(source, batch);\n      } catch (e) {\n        debugPrint('[ForYouFeed] Discover engine failed, falling back: $e');\n      }\n      try {\n        final music = await musicRecommendationEngine.generateForYou(\n"""
    new = """      try {\n        // Home and Discovery share the same primary recommendation pool.\n        // This keeps Discovery personalized instead of drifting into an\n        // unrelated random/trending feed.\n        final music = await musicRecommendationEngine.generateForYou(\n"""
    text = replace_once(text, old, new, 'for_you_feed_screen.dart: shared recommendation pool')

    # Keep the Discover engine as a controlled fallback after the shared pool.
    marker = """      } catch (e) {\n        debugPrint('[ForYouFeed] Music engine failed, falling back: $e');\n      }\n      // Fallback: existing personalized engine, then mood-biased pool.\n"""
    replacement = """      } catch (e) {\n        debugPrint('[ForYouFeed] Music engine failed, falling back: $e');\n      }\n      try {\n        final batch = await _discoverEngine.nextBatch(\n          excludeIds: _seenIds,\n          count: 12,\n          languages: _applied.languages.map((l) => l.token).toList(),\n          moods: biases,\n          regions: _applied.genres.map((g) => g.token).toList(),\n          config: engineConfig,\n        );\n        if (batch.isNotEmpty) return _refineForMode(source, batch);\n      } catch (e) {\n        debugPrint('[ForYouFeed] Discover fallback failed: $e');\n      }\n      // Final fallback: existing personalized engine, then mood-biased pool.\n"""
    text = replace_once(text, marker, replacement, 'for_you_feed_screen.dart: discover fallback')
    path.write_text(text)


def patch_main() -> None:
    path = ROOT / 'lib/main.dart'
    text = path.read_text()

    # A tiny global signal lets the Home screen scroll to top without exposing
    # its private controller through the navigation shell.
    anchor = "final ValueNotifier<int> currentTabIndexNotifier = ValueNotifier<int>(0);\n"
    if anchor not in text:
        raise SystemExit('main.dart: tab notifier anchor not found')
    if 'homeScrollToTopSignal' not in text:
        text = text.replace(
            anchor,
            anchor + "\n/// Incremented when Home is tapped while already selected.\nfinal ValueNotifier<int> homeScrollToTopSignal = ValueNotifier<int>(0);\n",
            1,
        )

    old = """                          setState(() {\n                            _index = target;\n                            currentTabIndexNotifier.value = target;\n                          });\n"""
    new = """                          setState(() {\n                            _index = target;\n                            currentTabIndexNotifier.value = target;\n                          });\n                          if (target == 0) {\n                            homeScrollToTopSignal.value++;\n                          }\n"""
    text = replace_once(text, old, new, 'main.dart: Home scroll-to-top')

    # Faster boot: only persistence needed for the first recommendation frame
    # blocks runApp. Network/notification/account initialization continues in
    # the background and remains available to later screens.
    old_boot = """  await Future.wait([\n    SupabaseService.initialize(),\n    LocalLibrary.instance.initialize(),\n    SignalStore.instance.initialize(),\n    PersonalizationStore.instance.initialize(),\n    RemoteConfigService.instance.init(),\n    AdFreeManager.instance.init(),\n    AppVersion.load(),\n    NotificationService.instance.initialize(),\n  ]);\n"""
    new_boot = """  await Future.wait([\n    LocalLibrary.instance.initialize(),\n    SignalStore.instance.initialize(),\n    PersonalizationStore.instance.initialize(),\n  ]);\n  // Non-critical services must never hold the first frame hostage. Home can\n  // render from local defaults immediately and reacts when remote config is\n  // ready; account/notification/backend services initialize in parallel.\n  unawaited(Future.wait([\n    SupabaseService.initialize(),\n    RemoteConfigService.instance.init(),\n    AdFreeManager.instance.init(),\n    AppVersion.load(),\n    NotificationService.instance.initialize(),\n  ]));\n"""
    text = replace_once(text, old_boot, new_boot, 'main.dart: fast boot')
    text = text.replace("  await AuthService.instance.initializeGoogleSignIn();\n", "  unawaited(AuthService.instance.initializeGoogleSignIn());\n", 1)
    text = text.replace("    Future.delayed(const Duration(seconds: 2), () {", "    Future.delayed(const Duration(milliseconds: 800), () {", 1)
    path.write_text(text)


def create_tests() -> None:
    path = ROOT / 'test/core/recommendation/recommendation_v2_policy_test.dart'
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return
    path.write_text(r'''import 'package:flutter_test/flutter_test.dart';

import '../../../lib/core/music/music_validator.dart';

void main() {
  const validator = MusicContentValidator();

  test('AI song is rejected even when provider marks it official', () {
    final result = validator.validate({
      'id': 'ai-1',
      'title': 'AI Generated Song - Love',
      'artist': 'Test Artist',
      'channelTitle': 'Official Music Channel',
      'duration': 210,
      'artwork': 'https://example.com/a.jpg',
      'channelId': 'channel-1',
      'isOfficial': true,
    });
    expect(result.isMusic, isFalse);
    expect(result.rejectionReason, 'UNOFFICIAL_AI_CONTENT');
  });

  test('AI music channel is rejected from channel metadata', () {
    final result = validator.validate({
      'id': 'ai-2',
      'title': 'Love Song',
      'artist': 'Artist',
      'channelTitle': 'AI Music Songs Official',
      'duration': 200,
      'artwork': 'https://example.com/a.jpg',
      'channelId': 'channel-2',
      'isOfficial': false,
    });
    expect(result.isMusic, isFalse);
  });
}
''')


def main() -> None:
    patch_validator()
    patch_repository()
    patch_candidate_generator()
    patch_home_feed()
    patch_home_screen()
    patch_discovery()
    patch_main()
    create_tests()
    print('Surgical Recommendation V2 + Home/Discovery polish patch applied.')


if __name__ == '__main__':
    main()
