from pathlib import Path


def patch(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    if new in text:
        return
    if old not in text:
        raise SystemExit(f'content-policy patch anchor not found: {path}')
    p.write_text(text.replace(old, new, 1))


# The validator is the single safety gate used by candidate generation and
# recommendation feeds. Keep the policy in source-control as a deterministic
# build patch, matching the existing dynamic/stability patch architecture.
patch(
    'lib/core/music/music_validator.dart',
    "import '../innertube/discovery_relevance.dart';\nimport 'music_canonicalizer.dart';",
    "import '../innertube/discovery_relevance.dart';\nimport 'music_canonicalizer.dart';\n\n// CONTENT_POLICY_PATCH: unofficial AI music is never recommended.\nconst List<String> _vShotsUnofficialAiMarkers = <String>[\n  'ai generated', 'ai-generated', 'ai generated song', 'ai-generated song',\n  'ai cover', 'ai-cover', 'ai voice', 'ai-voice', 'voice clone', 'voice-clone',\n  'deepfake voice', 'deepfake music', 'generated by ai', 'made with ai',\n  'suno ai', 'suno.com', 'udio ai', 'udio.com', 'ai music generator',\n  'ai music', 'artificial intelligence music',\n];\n\nbool _vShotsLooksLikeUnofficialAi(String title, String artist, String channel) {\n  final haystack = '$title $artist $channel'.toLowerCase();\n  return _vShotsUnofficialAiMarkers.any(haystack.contains);\n}")

patch(
    'lib/core/music/music_validator.dart',
    "    final artist = (track['artist'] as String?) ?? '';\n    final duration = track['duration'] as int? ?? 0;",
    "    final artist = (track['artist'] as String?) ?? '';\n    final channelTitle = (track['channelTitle'] as String?) ??\n        (track['channel'] as String?) ?? '';\n    final duration = track['duration'] as int? ?? 0;")

patch(
    'lib/core/music/music_validator.dart',
    "    final reasons = <String>[];\n\n    // STRONG non-music rejection (shared keyword set).",
    "    final reasons = <String>[];\n\n    // HARD POLICY: unofficial AI uploads are not recommendation content.\n    // Explicitly official/verified catalog items are allowed to continue.\n    if (!isOfficial &&\n        _vShotsLooksLikeUnofficialAi(title, artist, channelTitle)) {\n      return const MusicValidationResult(\n        isMusic: false,\n        confidence: 0.0,\n        reasons: ['UNOFFICIAL_AI_CONTENT'],\n        rejectionReason: 'UNOFFICIAL_AI_CONTENT',\n        sourceTrustScore: 0.0,\n      );\n    }\n\n    // STRONG non-music rejection (shared keyword set).")

# Discovery's regional trending pool should follow the device country rather
# than the remote-config default (which historically defaulted to IN).
patch(
    'lib/core/discover/discover_feed_engine.dart',
    "import '../recommendation/recommendation_service.dart';\nimport '../remote_config/remote_config_service.dart';",
    "import '../recommendation/recommendation_service.dart';\nimport '../recommendation/music_region_profile.dart';\nimport '../remote_config/remote_config_service.dart';")

patch(
    'lib/core/discover/discover_feed_engine.dart',
    "    final region = (cfg['region'] as String?)?.trim().isNotEmpty == true\n        ? (cfg['region'] as String).trim()\n        : 'IN';",
    "    // Country is automatic and permission-free. Explore filters still\n    // override the feed when explicitly selected by the user.\n    final region = MusicRegionProfile.current().countryCode;")
