// ═════════════════════════════════════════════════════════════════════════════
// V Shots — InnerTube normalizer
// ═════════════════════════════════════════════════════════════════════════════
//
// InnerTube → Normalizer → Recommendation Engine → Home / Discovery / Search.
//
// Maps raw InnerTube video items into the app's unified `ProviderTrack`
// shape and applies a quality filter so every provider produces a clean,
// playable, ORIGINAL-artist-first music surface. One videoId identity flows
// through the whole pipeline.
//
// Content policy:
//   • Official/verified uploads (OFFICIAL_ARTIST_BADGE, VERIFIED…) are
//     surfaced FIRST, so results favour real artist/label uploads over
//     fan and lyrics channels.
//   • Clearly non-music (podcast / interview / reaction / tutorial) and
//     strong unofficial-upload signals (lyrics / karaoke / slowed / reverb /
//     mashup / status) are dropped in the strict pass.
//   • If the strict pass leaves nothing, a RELAXED pass still returns
//     content (only non-music + duration excluded) so a shelf never appears
//     empty just because a query's results were dominated by unofficial
//     uploads.
// ═════════════════════════════════════════════════════════════════════════════

import '../../shared/utils/text_utils.dart';
import '../providers/provider_models.dart';
import 'inner_tube_models.dart';

class InnerTubeNormalizer {
  const InnerTubeNormalizer();

  /// Clearly non-music — filtered in BOTH passes.
  static const _nonMusicKeywords = [
    'podcast',
    'interview',
    'reaction',
    'tutorial',
  ];

  /// Strong "unofficial upload" signals — filtered in the STRICT pass only.
  static const _unofficialKeywords = [
    'lyrics',
    'lyrical',
    'karaoke',
    'slowed',
    'reverb',
    'nightcore',
    'mashup',
    'whatsapp status',
    'status video',
    'full screen status',
    'sped up',
    'edit audio',
    'cover song',
  ];

  /// AI-generated music markers — rejected in BOTH passes.
  static const _aiMusicKeywords = [
    'ai generated', 'ai-generated', 'ai cover', 'ai-cover',
    'ai voice', 'ai-voice', 'voice clone', 'voice-clone',
    'deepfake', 'suno', 'suno.ai', 'suno.com',
    'udio', 'udio.com', 'udio.ai', 'aiva',
    'soundraw', 'boomy', 'amper music',
    'ai music', 'artificial intelligence',
    'generated by ai', 'made with ai', 'ai song',
  ];

  /// Known AI music channel name markers — rejected regardless of title.
  static const _aiChannelMarkers = [
    'ai music', 'suno', 'udio', 'aiva',
    'soundraw', 'boomy', 'amper', 'deepfake', 'voice clone',
  ];

  bool _isNonMusic(String title) => _nonMusicKeywords.any(title.contains);
  bool _isUnofficial(String title) => _unofficialKeywords.any(title.contains);
  bool _isAiGenerated(String title, String channel) {
    final t = title.toLowerCase();
    final c = channel.toLowerCase();
    return _aiMusicKeywords.any(t.contains) ||
        _aiChannelMarkers.any(c.contains);
  }

  bool _withinDuration(
    InnerTubeVideoItem item, {
    required int maxMinutes,
    required int minMinutes,
  }) {
    final durationMinutes = item.durationSeconds / 60.0;
    if (durationMinutes > maxMinutes) return false;
    if (minMinutes > 0 && durationMinutes < minMinutes) return false;
    return true;
  }

  /// Strict playability: non-music, unofficial, AI-generated, duration caps.
  bool isPlayableMusic(
    InnerTubeVideoItem item, {
    int maxMinutes = 15,
    int minMinutes = 0,
  }) {
    final title = item.title.toLowerCase();
    if (_isNonMusic(title)) return false;
    if (_isUnofficial(title)) return false;
    if (_isAiGenerated(item.title, item.channelName)) return false;
    return _withinDuration(
      item,
      maxMinutes: maxMinutes,
      minMinutes: minMinutes,
    );
  }

  /// Relaxed playability: non-music + AI + duration (AI is ALWAYS rejected
  /// even in relaxed mode — we never surface AI-generated music).
  bool _isPlayableRelaxed(
    InnerTubeVideoItem item, {
    int maxMinutes = 15,
    int minMinutes = 0,
  }) {
    final title = item.title.toLowerCase();
    if (_isNonMusic(title)) return false;
    if (_isAiGenerated(item.title, item.channelName)) return false;
    return _withinDuration(
      item,
      maxMinutes: maxMinutes,
      minMinutes: minMinutes,
    );
  }

  ProviderTrack toProviderTrack(InnerTubeVideoItem item) {
    return ProviderTrack(
      id: item.videoId,
      title: cleanTitle(item.title, item.channelName),
      artist: item.channelName.isEmpty ? 'Unknown Artist' : item.channelName,
      artworkUrl: item.thumbnailUrl,
      durationSeconds: item.durationSeconds,
      isOfficial: item.isOfficial,
      channelId: item.channelId,
      viewCount: item.viewCount,
      publishedDaysAgo: item.publishedDaysAgo,
    );
  }

  /// Filters + maps a batch of InnerTube items in one pass, official-first.
  List<ProviderTrack> mapSearchResults(
    List<InnerTubeVideoItem> items, {
    required int limit,
    int maxMinutes = 15,
    int minMinutes = 0,
    Set<String> excludeIds = const {},
  }) {
    // De-duplicate by id first, preserving first-seen order.
    final seen = <String>{...excludeIds};
    final unique = <InnerTubeVideoItem>[];
    for (final item in items) {
      if (seen.add(item.videoId)) unique.add(item);
    }
    if (unique.isEmpty) return const [];

    // Official/verified uploads first (stable partition), then the rest.
    final official = <InnerTubeVideoItem>[];
    final rest = <InnerTubeVideoItem>[];
    for (final item in unique) {
      (item.isOfficial ? official : rest).add(item);
    }
    final ordered = <InnerTubeVideoItem>[...official, ...rest];

    final strict = _select(
      ordered,
      strict: true,
      limit: limit,
      maxMinutes: maxMinutes,
      minMinutes: minMinutes,
    );
    if (strict.isNotEmpty) return strict;

    // Relaxed fallback: only non-music + duration, so shelves never go empty.
    return _select(
      ordered,
      strict: false,
      limit: limit,
      maxMinutes: maxMinutes,
      minMinutes: minMinutes,
    );
  }

  List<ProviderTrack> _select(
    List<InnerTubeVideoItem> items, {
    required bool strict,
    required int limit,
    required int maxMinutes,
    required int minMinutes,
  }) {
    final result = <ProviderTrack>[];
    for (final item in items) {
      final ok = strict
          ? isPlayableMusic(
              item,
              maxMinutes: maxMinutes,
              minMinutes: minMinutes,
            )
          : _isPlayableRelaxed(
              item,
              maxMinutes: maxMinutes,
              minMinutes: minMinutes,
            );
      if (!ok) continue;
      result.add(toProviderTrack(item));
      if (result.length >= limit) break;
    }
    return result;
  }
}
